import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
/* eslint-disable no-console -- command progress is useful during long E2E runs */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
// The packed-tarball E2E intentionally uses Node's built-in runner.
// eslint-disable-next-line test/no-import-node-test
import { it } from 'node:test'
import { fileURLToPath } from 'node:url'
import { assertGeneratedFiles, assertGenerateOutput } from './assertions.mjs'
import { createWorkDirectory, run } from './helpers.mjs'

const repositoryRoot = fileURLToPath(new URL('../..', import.meta.url))
const createPackageRoot = join(repositoryRoot, 'create-clarity-theme')

it('packed create-clarity-theme tarball runs through its installed binary and generates a working consumer', { timeout: 25 * 60 * 1000 }, () => {
	const workDir = createWorkDirectory('create-clarity-tarball-')
	console.log(`  Work directory: ${workDir}`)

	try {
		run('pnpm', ['pack', '--pack-destination', workDir], repositoryRoot)
		const themeTarballPath = findTarball(workDir, /^clarity-theme-.*\.tgz$/)

		const harness = join(workDir, 'harness')
		const createTarballDir = join(workDir, 'create-tarball')
		mkdirSync(createTarballDir, { recursive: true })
		run('pnpm', ['--dir', createPackageRoot, 'pack', '--pack-destination', createTarballDir], repositoryRoot)
		const createTarballPath = findTarball(createTarballDir, /^create-clarity-theme-.*\.tgz$/)
		const createTarballFiles = execFileSync('tar', ['-tzf', createTarballPath], { encoding: 'utf8' })
		assert.match(createTarballFiles, /package\/templates\/default\/scripts\/new-blog\.mjs/)

		mkdirEmpty(harness)
		writeFileSync(join(harness, 'package.json'), `${JSON.stringify({
			name: 'create-clarity-tarball-harness',
			private: true,
			type: 'module',
			dependencies: {
				'create-clarity-theme': `file:${createTarballPath.replaceAll('\\', '/')}`,
			},
		}, null, 2)}\n`, { flag: 'wx' })
		run('pnpm', ['install', '--no-frozen-lockfile'], harness)

		run('pnpm', [
			'exec',
			'create-clarity-theme',
			'my-blog',
			'--yes',
			'--no-install',
			'--title',
			'Tarball E2E',
			'--description',
			'Consumer generated by the packed CLI',
			'--url',
			'https://create-e2e.example.com/',
			'--author',
			'Tarball E2E',
		], harness)

		const consumer = join(harness, 'my-blog')
		assertGeneratedFiles(consumer)
		const packagePath = join(consumer, 'package.json')
		const pkg = JSON.parse(readFileSync(packagePath, 'utf8'))
		pkg.dependencies['clarity-theme'] = `file:${themeTarballPath.replaceAll('\\', '/')}`
		writeFileSync(packagePath, `${JSON.stringify(pkg, null, 2)}\n`)

		run('pnpm', ['install', '--no-frozen-lockfile'], consumer)
		run('pnpm', ['new-blog', 'Tarball E2E Article', '--yes'], consumer)
		run('pnpm', ['exec', 'nuxt', 'typecheck'], consumer)
		run('pnpm', ['exec', 'nuxt', 'generate'], consumer)
		assertGenerateOutput(consumer, {
			expectedPosts: 2,
			titles: ['Tarball E2E Article'],
		})

		console.log('\n✔ Create CLI tarball E2E passed')
	}
	finally {
		if (process.exitCode !== 1) {
			rmSync(workDir, { recursive: true, force: true })
		}
		else {
			console.error(`  Debug directory retained: ${workDir}`)
		}
	}
})

function findTarball(directory, pattern) {
	const tarball = readdirSync(directory).find(file => pattern.test(file))
	assert.ok(tarball, `expected tarball matching ${pattern}`)
	return join(directory, tarball).replaceAll('\\', '/')
}

function mkdirEmpty(path) {
	mkdirSync(path, { recursive: true })
}
